@Base_URL = http://localhost:5042
@drinkId = b862a991-8240-4fe4-98a4-547fc6c34fb5

POST {{Base_URL}}/api/Drinks
Content-Type: application/json

{
    "name": "Mirinda",
    "price": 50
}

###

GET {{Base_URL}}/api/Drinks/{{drinkId}}

###

DELETE {{Base_URL}}/api/Drinks/{{drinkId}}

###

GET {{Base_URL}}/api/Drinks?page=1&pageSize=10