@Base_URL = http://localhost:5042
@drinkId = B6B347C5-D6BD-40BC-A997-F3F0846A88D9

POST {{Base_URL}}/api/Drinks
Content-Type: application/json

{
    "name": "Coca Cola",
    "price": 15
}

###

GET {{Base_URL}}/api/Drinks/{{drinkId}}

###

DELETE {{Base_URL}}/api/Drinks/{{drinkId}}
