@Base_URL = http://localhost:5042
@vendingMachine_Id = 78da5355-1552-49d6-a988-a8cf634cd83c
@drink_Id = E2F11CF4-D660-4284-A60A-963C808E8373
POST {{Base_URL}}/api/VendingMachines
Content-Type: application/json

{
    "model": "Z432"
}

###

GET {{Base_URL}}/api/VendingMachines/{{vendingMachine_Id}}

###

DELETE {{Base_URL}}/api/VendingMachines/{{vendingMachine_Id}}

###

POST  {{Base_URL}}/api/VendingMachines/{{vendingMachine_Id}}/drinks
Content-Type: application/json

{
    "drinkId": "6BB2915D-83B3-4EB5-A3AD-973C96D072EB"
}

###

GET  {{Base_URL}}/api/VendingMachines/{{vendingMachine_Id}}/drinks/{{drink_Id}}

###

POST {{Base_URL}}/api/VendingMachines/{{vendingMachine_Id}}/coins
Content-Type: application/json

{
    "coinId": "0692EFC9-DDF3-4728-B320-D34E7FE3EFC8"
}

###

GET {{Base_URL}}/api/VendingMachines/{{vendingMachine_Id}}/drinks?page=1&pageSize=10